// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NPLEditor.Templates.VSExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "NPLEditor.Templates.VSExtension.b2fd787a-0ec7-4579-bb6f-9fa3334677cf";
        public const string Name = "NPL Editor Extension";
        public const string Description = @"A graphical editor for '.npl' files used together with 'Nopipeline.Task' to produce '.mgcb' files for MonoGame projects.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "BlizzCrafter";
        public const string Tags = ".NET,C#,Game development,Templates,Games,Gamedev,Project,Mono,MonoGame,Nopipeline,NPL";
    }
}
