// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NPLEditor.Templates.VSExtension
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string NPLEditorTemplatesVSExtensionString = "7cfececb-3adc-4952-b954-32eed9df6a28";
        public static Guid NPLEditorTemplatesVSExtension = new Guid(NPLEditorTemplatesVSExtensionString);

        public const string NPLEditorFactoryString = "9bbbe19a-d951-4f48-8769-0e15f58c834c";
        public static Guid NPLEditorFactory = new Guid(NPLEditorFactoryString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {

    }
}