// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NPLEditor.VSExtension
{
    internal sealed partial class Vsix
    {
        public const string Id = "NPLEditor.VSExtension.b2fd787a-0ec7-4579-bb6f-9fa3334677cf";
        public const string Name = "NPL Editor Extension";
        public const string Description = @"The NPLEditor is a heavenly modernized and improved version of the MonoGame Pipeline Tool.";
        public const string Language = "en-US";
        public const string Version = "1.1.3";
        public const string Author = "BlizzCrafter";
        public const string Tags = ".NET,C#,Game development,Templates,Games,Gamedev,Project,Mono,MonoGame,MonoGo,Monofoxe,Nopipeline,NPL";
        public const bool IsPreview = false;
    }
}
